# docker-comopose.override.yml file for dev

services:
  web:
    build:
      context: .
      target: ${BUILD_TARGET:-dev} # dev
      args:
        - NODE_ENV=${NODE_ENV:-development}
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: Dockerfile
          action: rebuild
        - path: package.json
          action: rebuild
        - path: package-lock.json
          action: rebuild
        - path: next.config.ts
          action: rebuild
        - path: .
          target: /app
          action: sync
    restart: unless-stopped
