// Generated by scripts/i18n/gen-catalog-index.mjs — do not edit by hand.
// Static catalog map for React Native. The web app lazy-imports each
// (locale, namespace) chunk; Metro bundles them all and picks at runtime.

import akAuth from "@abonten/i18n/messages/ak/auth.json";
import akCommon from "@abonten/i18n/messages/ak/common.json";
import akEvents from "@abonten/i18n/messages/ak/events.json";
import akMetadata from "@abonten/i18n/messages/ak/metadata.json";
import akNavigation from "@abonten/i18n/messages/ak/navigation.json";
import akPlaces from "@abonten/i18n/messages/ak/places.json";
import akSettings from "@abonten/i18n/messages/ak/settings.json";
import deAuth from "@abonten/i18n/messages/de/auth.json";
import deCommon from "@abonten/i18n/messages/de/common.json";
import deEvents from "@abonten/i18n/messages/de/events.json";
import deMetadata from "@abonten/i18n/messages/de/metadata.json";
import deNavigation from "@abonten/i18n/messages/de/navigation.json";
import dePlaces from "@abonten/i18n/messages/de/places.json";
import deSettings from "@abonten/i18n/messages/de/settings.json";
import enAuth from "@abonten/i18n/messages/en/auth.json";
import enCommon from "@abonten/i18n/messages/en/common.json";
import enEvents from "@abonten/i18n/messages/en/events.json";
import enMetadata from "@abonten/i18n/messages/en/metadata.json";
import enNavigation from "@abonten/i18n/messages/en/navigation.json";
import enPlaces from "@abonten/i18n/messages/en/places.json";
import enSettings from "@abonten/i18n/messages/en/settings.json";
import esAuth from "@abonten/i18n/messages/es/auth.json";
import esCommon from "@abonten/i18n/messages/es/common.json";
import esEvents from "@abonten/i18n/messages/es/events.json";
import esMetadata from "@abonten/i18n/messages/es/metadata.json";
import esNavigation from "@abonten/i18n/messages/es/navigation.json";
import esPlaces from "@abonten/i18n/messages/es/places.json";
import esSettings from "@abonten/i18n/messages/es/settings.json";
import frAuth from "@abonten/i18n/messages/fr/auth.json";
import frCommon from "@abonten/i18n/messages/fr/common.json";
import frEvents from "@abonten/i18n/messages/fr/events.json";
import frMetadata from "@abonten/i18n/messages/fr/metadata.json";
import frNavigation from "@abonten/i18n/messages/fr/navigation.json";
import frPlaces from "@abonten/i18n/messages/fr/places.json";
import frSettings from "@abonten/i18n/messages/fr/settings.json";
import ptAuth from "@abonten/i18n/messages/pt/auth.json";
import ptCommon from "@abonten/i18n/messages/pt/common.json";
import ptEvents from "@abonten/i18n/messages/pt/events.json";
import ptMetadata from "@abonten/i18n/messages/pt/metadata.json";
import ptNavigation from "@abonten/i18n/messages/pt/navigation.json";
import ptPlaces from "@abonten/i18n/messages/pt/places.json";
import ptSettings from "@abonten/i18n/messages/pt/settings.json";
import type { I18nLocale } from "@abonten/i18n/namespaces";

export type Messages = Record<string, unknown>;
export type LocaleMessages = Record<string, Messages>;

export const CATALOG: Record<I18nLocale, LocaleMessages> = {
  en: {
    auth: enAuth,
    common: enCommon,
    events: enEvents,
    metadata: enMetadata,
    navigation: enNavigation,
    places: enPlaces,
    settings: enSettings,
  },
  ak: {
    auth: akAuth,
    common: akCommon,
    events: akEvents,
    metadata: akMetadata,
    navigation: akNavigation,
    places: akPlaces,
    settings: akSettings,
  },
  de: {
    auth: deAuth,
    common: deCommon,
    events: deEvents,
    metadata: deMetadata,
    navigation: deNavigation,
    places: dePlaces,
    settings: deSettings,
  },
  es: {
    auth: esAuth,
    common: esCommon,
    events: esEvents,
    metadata: esMetadata,
    navigation: esNavigation,
    places: esPlaces,
    settings: esSettings,
  },
  fr: {
    auth: frAuth,
    common: frCommon,
    events: frEvents,
    metadata: frMetadata,
    navigation: frNavigation,
    places: frPlaces,
    settings: frSettings,
  },
  pt: {
    auth: ptAuth,
    common: ptCommon,
    events: ptEvents,
    metadata: ptMetadata,
    navigation: ptNavigation,
    places: ptPlaces,
    settings: ptSettings,
  },
};
