// Generated by scripts/i18n/gen-catalog-index.mjs — do not edit by hand.
// Static catalog map for React Native. The web app lazy-imports each
// (locale, namespace) chunk; Metro bundles them all and picks at runtime.

import akAccount from "@abonten/i18n/messages/ak/account.json";
import akAuth from "@abonten/i18n/messages/ak/auth.json";
import akCheckout from "@abonten/i18n/messages/ak/checkout.json";
import akCommon from "@abonten/i18n/messages/ak/common.json";
import akCore from "@abonten/i18n/messages/ak/core.json";
import akDiscovery from "@abonten/i18n/messages/ak/discovery.json";
import akEvents from "@abonten/i18n/messages/ak/events.json";
import akExplore from "@abonten/i18n/messages/ak/explore.json";
import akFatal from "@abonten/i18n/messages/ak/fatal.json";
import akFieldOps from "@abonten/i18n/messages/ak/fieldOps.json";
import akFinances from "@abonten/i18n/messages/ak/finances.json";
import akHelp from "@abonten/i18n/messages/ak/help.json";
import akLanding from "@abonten/i18n/messages/ak/landing.json";
import akLegal from "@abonten/i18n/messages/ak/legal.json";
import akManage from "@abonten/i18n/messages/ak/manage.json";
import akMessaging from "@abonten/i18n/messages/ak/messaging.json";
import akMetadata from "@abonten/i18n/messages/ak/metadata.json";
import akNavigation from "@abonten/i18n/messages/ak/navigation.json";
import akNotifications from "@abonten/i18n/messages/ak/notifications.json";
import akPlaces from "@abonten/i18n/messages/ak/places.json";
import akPlans from "@abonten/i18n/messages/ak/plans.json";
import akProfile from "@abonten/i18n/messages/ak/profile.json";
import akReviews from "@abonten/i18n/messages/ak/reviews.json";
import akRewards from "@abonten/i18n/messages/ak/rewards.json";
import akSearch from "@abonten/i18n/messages/ak/search.json";
import akSettings from "@abonten/i18n/messages/ak/settings.json";
import akSpotlight from "@abonten/i18n/messages/ak/spotlight.json";
import akTickets from "@abonten/i18n/messages/ak/tickets.json";
import akTransactions from "@abonten/i18n/messages/ak/transactions.json";
import akValidation from "@abonten/i18n/messages/ak/validation.json";
import akVerification from "@abonten/i18n/messages/ak/verification.json";
import akWallet from "@abonten/i18n/messages/ak/wallet.json";
import akWeekly from "@abonten/i18n/messages/ak/weekly.json";
import deAccount from "@abonten/i18n/messages/de/account.json";
import deAuth from "@abonten/i18n/messages/de/auth.json";
import deCheckout from "@abonten/i18n/messages/de/checkout.json";
import deCommon from "@abonten/i18n/messages/de/common.json";
import deCore from "@abonten/i18n/messages/de/core.json";
import deDiscovery from "@abonten/i18n/messages/de/discovery.json";
import deEvents from "@abonten/i18n/messages/de/events.json";
import deExplore from "@abonten/i18n/messages/de/explore.json";
import deFatal from "@abonten/i18n/messages/de/fatal.json";
import deFieldOps from "@abonten/i18n/messages/de/fieldOps.json";
import deFinances from "@abonten/i18n/messages/de/finances.json";
import deHelp from "@abonten/i18n/messages/de/help.json";
import deLanding from "@abonten/i18n/messages/de/landing.json";
import deLegal from "@abonten/i18n/messages/de/legal.json";
import deManage from "@abonten/i18n/messages/de/manage.json";
import deMessaging from "@abonten/i18n/messages/de/messaging.json";
import deMetadata from "@abonten/i18n/messages/de/metadata.json";
import deNavigation from "@abonten/i18n/messages/de/navigation.json";
import deNotifications from "@abonten/i18n/messages/de/notifications.json";
import dePlaces from "@abonten/i18n/messages/de/places.json";
import dePlans from "@abonten/i18n/messages/de/plans.json";
import deProfile from "@abonten/i18n/messages/de/profile.json";
import deReviews from "@abonten/i18n/messages/de/reviews.json";
import deRewards from "@abonten/i18n/messages/de/rewards.json";
import deSearch from "@abonten/i18n/messages/de/search.json";
import deSettings from "@abonten/i18n/messages/de/settings.json";
import deSpotlight from "@abonten/i18n/messages/de/spotlight.json";
import deTickets from "@abonten/i18n/messages/de/tickets.json";
import deTransactions from "@abonten/i18n/messages/de/transactions.json";
import deValidation from "@abonten/i18n/messages/de/validation.json";
import deVerification from "@abonten/i18n/messages/de/verification.json";
import deWallet from "@abonten/i18n/messages/de/wallet.json";
import deWeekly from "@abonten/i18n/messages/de/weekly.json";
import enAccount from "@abonten/i18n/messages/en/account.json";
import enAuth from "@abonten/i18n/messages/en/auth.json";
import enCheckout from "@abonten/i18n/messages/en/checkout.json";
import enCommon from "@abonten/i18n/messages/en/common.json";
import enCore from "@abonten/i18n/messages/en/core.json";
import enDiscovery from "@abonten/i18n/messages/en/discovery.json";
import enEvents from "@abonten/i18n/messages/en/events.json";
import enExplore from "@abonten/i18n/messages/en/explore.json";
import enFatal from "@abonten/i18n/messages/en/fatal.json";
import enFieldOps from "@abonten/i18n/messages/en/fieldOps.json";
import enFinances from "@abonten/i18n/messages/en/finances.json";
import enHelp from "@abonten/i18n/messages/en/help.json";
import enLanding from "@abonten/i18n/messages/en/landing.json";
import enLegal from "@abonten/i18n/messages/en/legal.json";
import enManage from "@abonten/i18n/messages/en/manage.json";
import enMessaging from "@abonten/i18n/messages/en/messaging.json";
import enMetadata from "@abonten/i18n/messages/en/metadata.json";
import enNavigation from "@abonten/i18n/messages/en/navigation.json";
import enNotifications from "@abonten/i18n/messages/en/notifications.json";
import enPlaces from "@abonten/i18n/messages/en/places.json";
import enPlans from "@abonten/i18n/messages/en/plans.json";
import enProfile from "@abonten/i18n/messages/en/profile.json";
import enReviews from "@abonten/i18n/messages/en/reviews.json";
import enRewards from "@abonten/i18n/messages/en/rewards.json";
import enSearch from "@abonten/i18n/messages/en/search.json";
import enSettings from "@abonten/i18n/messages/en/settings.json";
import enSpotlight from "@abonten/i18n/messages/en/spotlight.json";
import enTickets from "@abonten/i18n/messages/en/tickets.json";
import enTransactions from "@abonten/i18n/messages/en/transactions.json";
import enValidation from "@abonten/i18n/messages/en/validation.json";
import enVerification from "@abonten/i18n/messages/en/verification.json";
import enWallet from "@abonten/i18n/messages/en/wallet.json";
import enWeekly from "@abonten/i18n/messages/en/weekly.json";
import esAccount from "@abonten/i18n/messages/es/account.json";
import esAuth from "@abonten/i18n/messages/es/auth.json";
import esCheckout from "@abonten/i18n/messages/es/checkout.json";
import esCommon from "@abonten/i18n/messages/es/common.json";
import esCore from "@abonten/i18n/messages/es/core.json";
import esDiscovery from "@abonten/i18n/messages/es/discovery.json";
import esEvents from "@abonten/i18n/messages/es/events.json";
import esExplore from "@abonten/i18n/messages/es/explore.json";
import esFatal from "@abonten/i18n/messages/es/fatal.json";
import esFieldOps from "@abonten/i18n/messages/es/fieldOps.json";
import esFinances from "@abonten/i18n/messages/es/finances.json";
import esHelp from "@abonten/i18n/messages/es/help.json";
import esLanding from "@abonten/i18n/messages/es/landing.json";
import esLegal from "@abonten/i18n/messages/es/legal.json";
import esManage from "@abonten/i18n/messages/es/manage.json";
import esMessaging from "@abonten/i18n/messages/es/messaging.json";
import esMetadata from "@abonten/i18n/messages/es/metadata.json";
import esNavigation from "@abonten/i18n/messages/es/navigation.json";
import esNotifications from "@abonten/i18n/messages/es/notifications.json";
import esPlaces from "@abonten/i18n/messages/es/places.json";
import esPlans from "@abonten/i18n/messages/es/plans.json";
import esProfile from "@abonten/i18n/messages/es/profile.json";
import esReviews from "@abonten/i18n/messages/es/reviews.json";
import esRewards from "@abonten/i18n/messages/es/rewards.json";
import esSearch from "@abonten/i18n/messages/es/search.json";
import esSettings from "@abonten/i18n/messages/es/settings.json";
import esSpotlight from "@abonten/i18n/messages/es/spotlight.json";
import esTickets from "@abonten/i18n/messages/es/tickets.json";
import esTransactions from "@abonten/i18n/messages/es/transactions.json";
import esValidation from "@abonten/i18n/messages/es/validation.json";
import esVerification from "@abonten/i18n/messages/es/verification.json";
import esWallet from "@abonten/i18n/messages/es/wallet.json";
import esWeekly from "@abonten/i18n/messages/es/weekly.json";
import frAccount from "@abonten/i18n/messages/fr/account.json";
import frAuth from "@abonten/i18n/messages/fr/auth.json";
import frCheckout from "@abonten/i18n/messages/fr/checkout.json";
import frCommon from "@abonten/i18n/messages/fr/common.json";
import frCore from "@abonten/i18n/messages/fr/core.json";
import frDiscovery from "@abonten/i18n/messages/fr/discovery.json";
import frEvents from "@abonten/i18n/messages/fr/events.json";
import frExplore from "@abonten/i18n/messages/fr/explore.json";
import frFatal from "@abonten/i18n/messages/fr/fatal.json";
import frFieldOps from "@abonten/i18n/messages/fr/fieldOps.json";
import frFinances from "@abonten/i18n/messages/fr/finances.json";
import frHelp from "@abonten/i18n/messages/fr/help.json";
import frLanding from "@abonten/i18n/messages/fr/landing.json";
import frLegal from "@abonten/i18n/messages/fr/legal.json";
import frManage from "@abonten/i18n/messages/fr/manage.json";
import frMessaging from "@abonten/i18n/messages/fr/messaging.json";
import frMetadata from "@abonten/i18n/messages/fr/metadata.json";
import frNavigation from "@abonten/i18n/messages/fr/navigation.json";
import frNotifications from "@abonten/i18n/messages/fr/notifications.json";
import frPlaces from "@abonten/i18n/messages/fr/places.json";
import frPlans from "@abonten/i18n/messages/fr/plans.json";
import frProfile from "@abonten/i18n/messages/fr/profile.json";
import frReviews from "@abonten/i18n/messages/fr/reviews.json";
import frRewards from "@abonten/i18n/messages/fr/rewards.json";
import frSearch from "@abonten/i18n/messages/fr/search.json";
import frSettings from "@abonten/i18n/messages/fr/settings.json";
import frSpotlight from "@abonten/i18n/messages/fr/spotlight.json";
import frTickets from "@abonten/i18n/messages/fr/tickets.json";
import frTransactions from "@abonten/i18n/messages/fr/transactions.json";
import frValidation from "@abonten/i18n/messages/fr/validation.json";
import frVerification from "@abonten/i18n/messages/fr/verification.json";
import frWallet from "@abonten/i18n/messages/fr/wallet.json";
import frWeekly from "@abonten/i18n/messages/fr/weekly.json";
import ptAccount from "@abonten/i18n/messages/pt/account.json";
import ptAuth from "@abonten/i18n/messages/pt/auth.json";
import ptCheckout from "@abonten/i18n/messages/pt/checkout.json";
import ptCommon from "@abonten/i18n/messages/pt/common.json";
import ptCore from "@abonten/i18n/messages/pt/core.json";
import ptDiscovery from "@abonten/i18n/messages/pt/discovery.json";
import ptEvents from "@abonten/i18n/messages/pt/events.json";
import ptExplore from "@abonten/i18n/messages/pt/explore.json";
import ptFatal from "@abonten/i18n/messages/pt/fatal.json";
import ptFieldOps from "@abonten/i18n/messages/pt/fieldOps.json";
import ptFinances from "@abonten/i18n/messages/pt/finances.json";
import ptHelp from "@abonten/i18n/messages/pt/help.json";
import ptLanding from "@abonten/i18n/messages/pt/landing.json";
import ptLegal from "@abonten/i18n/messages/pt/legal.json";
import ptManage from "@abonten/i18n/messages/pt/manage.json";
import ptMessaging from "@abonten/i18n/messages/pt/messaging.json";
import ptMetadata from "@abonten/i18n/messages/pt/metadata.json";
import ptNavigation from "@abonten/i18n/messages/pt/navigation.json";
import ptNotifications from "@abonten/i18n/messages/pt/notifications.json";
import ptPlaces from "@abonten/i18n/messages/pt/places.json";
import ptPlans from "@abonten/i18n/messages/pt/plans.json";
import ptProfile from "@abonten/i18n/messages/pt/profile.json";
import ptReviews from "@abonten/i18n/messages/pt/reviews.json";
import ptRewards from "@abonten/i18n/messages/pt/rewards.json";
import ptSearch from "@abonten/i18n/messages/pt/search.json";
import ptSettings from "@abonten/i18n/messages/pt/settings.json";
import ptSpotlight from "@abonten/i18n/messages/pt/spotlight.json";
import ptTickets from "@abonten/i18n/messages/pt/tickets.json";
import ptTransactions from "@abonten/i18n/messages/pt/transactions.json";
import ptValidation from "@abonten/i18n/messages/pt/validation.json";
import ptVerification from "@abonten/i18n/messages/pt/verification.json";
import ptWallet from "@abonten/i18n/messages/pt/wallet.json";
import ptWeekly from "@abonten/i18n/messages/pt/weekly.json";
import type { I18nLocale } from "@abonten/i18n/namespaces";

export type Messages = Record<string, unknown>;
export type LocaleMessages = Record<string, Messages>;

export const CATALOG: Record<I18nLocale, LocaleMessages> = {
  en: {
    account: enAccount,
    auth: enAuth,
    checkout: enCheckout,
    common: enCommon,
    core: enCore,
    discovery: enDiscovery,
    events: enEvents,
    explore: enExplore,
    fatal: enFatal,
    fieldOps: enFieldOps,
    finances: enFinances,
    help: enHelp,
    landing: enLanding,
    legal: enLegal,
    manage: enManage,
    messaging: enMessaging,
    metadata: enMetadata,
    navigation: enNavigation,
    notifications: enNotifications,
    places: enPlaces,
    plans: enPlans,
    profile: enProfile,
    reviews: enReviews,
    rewards: enRewards,
    search: enSearch,
    settings: enSettings,
    spotlight: enSpotlight,
    tickets: enTickets,
    transactions: enTransactions,
    validation: enValidation,
    verification: enVerification,
    wallet: enWallet,
    weekly: enWeekly,
  },
  ak: {
    account: akAccount,
    auth: akAuth,
    checkout: akCheckout,
    common: akCommon,
    core: akCore,
    discovery: akDiscovery,
    events: akEvents,
    explore: akExplore,
    fatal: akFatal,
    fieldOps: akFieldOps,
    finances: akFinances,
    help: akHelp,
    landing: akLanding,
    legal: akLegal,
    manage: akManage,
    messaging: akMessaging,
    metadata: akMetadata,
    navigation: akNavigation,
    notifications: akNotifications,
    places: akPlaces,
    plans: akPlans,
    profile: akProfile,
    reviews: akReviews,
    rewards: akRewards,
    search: akSearch,
    settings: akSettings,
    spotlight: akSpotlight,
    tickets: akTickets,
    transactions: akTransactions,
    validation: akValidation,
    verification: akVerification,
    wallet: akWallet,
    weekly: akWeekly,
  },
  de: {
    account: deAccount,
    auth: deAuth,
    checkout: deCheckout,
    common: deCommon,
    core: deCore,
    discovery: deDiscovery,
    events: deEvents,
    explore: deExplore,
    fatal: deFatal,
    fieldOps: deFieldOps,
    finances: deFinances,
    help: deHelp,
    landing: deLanding,
    legal: deLegal,
    manage: deManage,
    messaging: deMessaging,
    metadata: deMetadata,
    navigation: deNavigation,
    notifications: deNotifications,
    places: dePlaces,
    plans: dePlans,
    profile: deProfile,
    reviews: deReviews,
    rewards: deRewards,
    search: deSearch,
    settings: deSettings,
    spotlight: deSpotlight,
    tickets: deTickets,
    transactions: deTransactions,
    validation: deValidation,
    verification: deVerification,
    wallet: deWallet,
    weekly: deWeekly,
  },
  es: {
    account: esAccount,
    auth: esAuth,
    checkout: esCheckout,
    common: esCommon,
    core: esCore,
    discovery: esDiscovery,
    events: esEvents,
    explore: esExplore,
    fatal: esFatal,
    fieldOps: esFieldOps,
    finances: esFinances,
    help: esHelp,
    landing: esLanding,
    legal: esLegal,
    manage: esManage,
    messaging: esMessaging,
    metadata: esMetadata,
    navigation: esNavigation,
    notifications: esNotifications,
    places: esPlaces,
    plans: esPlans,
    profile: esProfile,
    reviews: esReviews,
    rewards: esRewards,
    search: esSearch,
    settings: esSettings,
    spotlight: esSpotlight,
    tickets: esTickets,
    transactions: esTransactions,
    validation: esValidation,
    verification: esVerification,
    wallet: esWallet,
    weekly: esWeekly,
  },
  fr: {
    account: frAccount,
    auth: frAuth,
    checkout: frCheckout,
    common: frCommon,
    core: frCore,
    discovery: frDiscovery,
    events: frEvents,
    explore: frExplore,
    fatal: frFatal,
    fieldOps: frFieldOps,
    finances: frFinances,
    help: frHelp,
    landing: frLanding,
    legal: frLegal,
    manage: frManage,
    messaging: frMessaging,
    metadata: frMetadata,
    navigation: frNavigation,
    notifications: frNotifications,
    places: frPlaces,
    plans: frPlans,
    profile: frProfile,
    reviews: frReviews,
    rewards: frRewards,
    search: frSearch,
    settings: frSettings,
    spotlight: frSpotlight,
    tickets: frTickets,
    transactions: frTransactions,
    validation: frValidation,
    verification: frVerification,
    wallet: frWallet,
    weekly: frWeekly,
  },
  pt: {
    account: ptAccount,
    auth: ptAuth,
    checkout: ptCheckout,
    common: ptCommon,
    core: ptCore,
    discovery: ptDiscovery,
    events: ptEvents,
    explore: ptExplore,
    fatal: ptFatal,
    fieldOps: ptFieldOps,
    finances: ptFinances,
    help: ptHelp,
    landing: ptLanding,
    legal: ptLegal,
    manage: ptManage,
    messaging: ptMessaging,
    metadata: ptMetadata,
    navigation: ptNavigation,
    notifications: ptNotifications,
    places: ptPlaces,
    plans: ptPlans,
    profile: ptProfile,
    reviews: ptReviews,
    rewards: ptRewards,
    search: ptSearch,
    settings: ptSettings,
    spotlight: ptSpotlight,
    tickets: ptTickets,
    transactions: ptTransactions,
    validation: ptValidation,
    verification: ptVerification,
    wallet: ptWallet,
    weekly: ptWeekly,
  },
};
