export const eventCategoriesAndTypes = [
  {
    category: "Music & Concerts",
    types: [
      "Live Concerts",
      "DJ Parties",
      "Music Festivals",
      "Artist Tours",
      "Listening Parties",
      "Album Launches",
      "Open Mic Nights",
      "Karaoke Events",
      "Choir Performances",
      "Gospel Concerts",
      "Battle of the Bands",
      "Instrumental Performances",
      "Indie Music Shows",
    ],
  },
  {
    category: "Arts, Culture & Theatre",
    types: [
      "Drama & Theatre Shows",
      "Cultural Festivals",
      "Poetry Slams",
      "Art Exhibitions",
      "Dance Performances",
      "Storytelling Nights",
      "Book Readings",
      "Gallery Tours",
      "Puppetry Shows",
      "Folklore Events",
      "Calligraphy Events",
      "Craft Fairs",
      "Traditional Dances",
    ],
  },
  {
    category: "Entertainment & Shows",
    types: [
      "Comedy Shows",
      "Magic Shows",
      "Talent Shows",
      "Variety Shows",
      "Street Performances",
      "Circus Acts",
      "Illusion Shows",
      "Musical Theatre",
      "Game Shows (Live)",
      "TV Show Recordings",
      "Improv Nights",
      "Fan Meetups",
    ],
  },
  {
    category: "Spirituality & Religion",
    types: [
      "Church Conferences",
      "Worship Nights",
      "Revival Meetings",
      "Meditation Retreats",
      "Interfaith Dialogues",
      "Healing Services",
      "Spiritual Workshops",
      "Quran Recitation Events",
      "Buddhist Teachings",
      "Hindu Festivals",
      "Fasting/Prayer Camps",
      "Bible Study Camps",
      "Pilgrimage Info Events",
      "Gospel Music Events",
      "Zen Retreats",
      "Spiritual Counseling Sessions",
    ],
  },
  {
    category: "Education & Training",
    types: [
      "Academic Seminars",
      "Workshops & Bootcamps",
      "Career Fairs",
      "Conferences & Summits",
      "Thesis Presentations",
      "Graduation Events",
      "Continuing Education Courses",
      "Public Lectures",
      "Study Abroad Info Sessions",
      "Campus Events",
      "Educational Webinars",
      "Language Learning Events",
      "STEM Events",
    ],
  },
  {
    category: "Business & Professional",
    types: [
      "Networking Events",
      "Product Launches",
      "Investor Meetups",
      "Corporate Retreats",
      "Company Anniversary Parties",
      "Startup Pitches",
      "Business Expos",
      "Job Fairs",
      "Entrepreneurship Bootcamps",
      "Co-working Meetups",
      "Sales & Marketing Summits",
      "Leadership Workshops",
      "Franchise Shows",
    ],
  },
  {
    category: "Tech & Innovation",
    types: [
      "Hackathons",
      "Tech Meetups",
      "AI & ML Conferences",
      "Web3 Events",
      "Startup Showcases",
      "Developer Bootcamps",
      "App/Product Demos",
      "Gaming Events",
      "Robotics Fairs",
      "Coding Competitions",
      "Tech Expos",
      "Gadget Launches",
      "Blockchain Conferences",
    ],
  },
  {
    category: "Charity & Causes",
    types: [
      "Fundraising Events",
      "Nonprofit Galas",
      "Community Outreach",
      "Blood Donation Drives",
      "Clean-up Campaigns",
      "Mental Health Awareness",
      "Animal Rescue Fundraisers",
      "Food Drives",
      "Disaster Relief Appeals",
      "Social Justice Rallies",
      "Charity Walks & Runs",
      "Volunteering Events",
    ],
  },
  {
    category: "Sports & Fitness",
    types: [
      "Marathons & Runs",
      "Soccer/Football Matches",
      "Fitness Bootcamps",
      "Yoga Sessions",
      "Dance Workouts",
      "Martial Arts Events",
      "Zumba Classes",
      "CrossFit Challenges",
      "Esports Tournaments",
      "Bike Races",
      "Bodybuilding Competitions",
      "Climbing Events",
      "Skating Events",
      "Swimming Competitions",
    ],
  },
  {
    category: "Food & Drink",
    types: [
      "Food Festivals",
      "Wine Tastings",
      "Cooking Classes",
      "Chef Competitions",
      "Restaurant Launches",
      "Vegan/Vegetarian Events",
      "BBQ Events",
      "Cocktail Parties",
      "Street Food Events",
      "Brew Tastings",
      "Home Cooking Workshops",
      "Baking Events",
    ],
  },
  {
    category: "Family & Kids",
    types: [
      "Family Fun Days",
      "Children’s Shows",
      "Parenting Seminars",
      "Kids Talent Shows",
      "Family Camping Events",
      "School Events",
      "Puppet Shows",
      "Petting Zoo Events",
      "Toy & Book Fairs",
      "Birthday Parties",
      "Children's Workshops",
      "Playdates & Playgroups",
    ],
  },
  {
    category: "Fashion & Beauty",
    types: [
      "Fashion Shows",
      "Beauty Masterclasses",
      "Makeup Tutorials",
      "Hair Styling Workshops",
      "Clothing Pop-Ups",
      "Boutique Openings",
      "Modeling Auditions",
      "Fashion Design Talks",
      "Grooming Workshops",
      "Cosmetics Expos",
    ],
  },
  {
    category: "Nature, Travel & Adventure",
    types: [
      "Camping Trips",
      "Hiking Tours",
      "Safari Adventures",
      "Eco-Tourism Events",
      "Travel Expos",
      "Nature Retreats",
      "Beach Parties",
      "Boat Cruises",
      "Glamping Events",
      "Mountaineering Events",
      "Backpacking Meetups",
      "Birdwatching Tours",
    ],
  },
  {
    category: "Lifestyle & Hobbies",
    types: [
      "Gardening Workshops",
      "Home Décor Events",
      "DIY Craft Events",
      "Photography Meetups",
      "Journaling Retreats",
      "Car Shows",
      "Book Clubs",
      "Board Game Nights",
      "Knitting Circles",
      "Antique Markets",
      "Minimalism Workshops",
    ],
  },
  {
    category: "Parties & Social Events",
    types: [
      "Birthday Parties",
      "Beach Parties",
      "House Parties",
      "Pool Parties",
      "Bachelor/Bachelorette Parties",
      "Meet & Greets",
      "Club Nights",
      "Social Mixers",
      "Themed Costume Parties",
      "Sunset Sessions",
    ],
  },
  {
    category: "Love, Dating & Relationships",
    types: [
      "Speed Dating",
      "Relationship Seminars",
      "Couple Retreats",
      "Singles Mixers",
      "Matchmaking Events",
      "Wedding Expos",
      "Engagement Parties",
      "Love Language Workshops",
    ],
  },
  {
    category: "Civic & Government",
    types: [
      "Political Rallies",
      "Town Hall Meetings",
      "Government Trainings",
      "Citizenship Drives",
      "Legal Aid Events",
      "Voter Registration Campaigns",
      "Policy Discussion Forums",
      "Public Safety Events",
    ],
  },
  {
    category: "Personal Development",
    types: [
      "Life Coaching Sessions",
      "Vision Board Workshops",
      "Motivational Talks",
      "Self-Help Retreats",
      "Public Speaking Classes",
      "Financial Literacy Events",
      "Time Management Training",
      "Confidence Building Workshops",
      "Mindfulness Sessions",
    ],
  },
  {
    category: "Life Events & Ceremonies",
    types: [
      "Weddings",
      "Engagement Ceremonies",
      "Anniversary Celebrations",
      "Bridal Showers",
      "Bachelor/Bachelorette Parties",
      "Naming Ceremonies",
      "Dedications",
      "Graduation Parties",
      "Housewarming Events",
      "Funerals & Memorials",
      "Retirement Celebrations",
      "Baby Showers",
      "Christening Events",
    ],
  },
];
