// Curated starting defaults for a market: what an administrator sees
// pre-filled when they add a country in Admin › Markets. Verified by hand,
// kept to countries Abonten could plausibly open; anything else starts blank
// and the admin fills it in. NOT a source of truth at runtime — the `market`
// row is.

import type { DistanceUnit } from "../units/distance";

export type CountryDefaults = {
  currency: string;
  timeZone: string;
  locale: string;
  distanceUnit: DistanceUnit;
  /** ISO 3166-2 style region kind label for the address form. */
  regionLabel: string;
  postalCodeRequired: boolean;
};

export const COUNTRY_DEFAULTS: Readonly<Record<string, CountryDefaults>> = {
  GH: {
    currency: "GHS",
    timeZone: "Africa/Accra",
    locale: "en-GH",
    distanceUnit: "km",
    regionLabel: "Region",
    postalCodeRequired: false,
  },
  NG: {
    currency: "NGN",
    timeZone: "Africa/Lagos",
    locale: "en-NG",
    distanceUnit: "km",
    regionLabel: "State",
    postalCodeRequired: false,
  },
  KE: {
    currency: "KES",
    timeZone: "Africa/Nairobi",
    locale: "en-KE",
    distanceUnit: "km",
    regionLabel: "County",
    postalCodeRequired: false,
  },
  ZA: {
    currency: "ZAR",
    timeZone: "Africa/Johannesburg",
    locale: "en-ZA",
    distanceUnit: "km",
    regionLabel: "Province",
    postalCodeRequired: true,
  },
  CI: {
    currency: "XOF",
    timeZone: "Africa/Abidjan",
    locale: "fr-CI",
    distanceUnit: "km",
    regionLabel: "Région",
    postalCodeRequired: false,
  },
  SN: {
    currency: "XOF",
    timeZone: "Africa/Dakar",
    locale: "fr-SN",
    distanceUnit: "km",
    regionLabel: "Région",
    postalCodeRequired: false,
  },
  TG: {
    currency: "XOF",
    timeZone: "Africa/Lome",
    locale: "fr-TG",
    distanceUnit: "km",
    regionLabel: "Région",
    postalCodeRequired: false,
  },
  BJ: {
    currency: "XOF",
    timeZone: "Africa/Porto-Novo",
    locale: "fr-BJ",
    distanceUnit: "km",
    regionLabel: "Département",
    postalCodeRequired: false,
  },
  CM: {
    currency: "XAF",
    timeZone: "Africa/Douala",
    locale: "fr-CM",
    distanceUnit: "km",
    regionLabel: "Région",
    postalCodeRequired: false,
  },
  RW: {
    currency: "RWF",
    timeZone: "Africa/Kigali",
    locale: "en-RW",
    distanceUnit: "km",
    regionLabel: "Province",
    postalCodeRequired: false,
  },
  UG: {
    currency: "UGX",
    timeZone: "Africa/Kampala",
    locale: "en-UG",
    distanceUnit: "km",
    regionLabel: "District",
    postalCodeRequired: false,
  },
  TZ: {
    currency: "TZS",
    timeZone: "Africa/Dar_es_Salaam",
    locale: "en-TZ",
    distanceUnit: "km",
    regionLabel: "Region",
    postalCodeRequired: false,
  },
  ET: {
    currency: "ETB",
    timeZone: "Africa/Addis_Ababa",
    locale: "en-ET",
    distanceUnit: "km",
    regionLabel: "Region",
    postalCodeRequired: false,
  },
  EG: {
    currency: "EGP",
    timeZone: "Africa/Cairo",
    locale: "ar-EG",
    distanceUnit: "km",
    regionLabel: "Governorate",
    postalCodeRequired: false,
  },
  MA: {
    currency: "MAD",
    timeZone: "Africa/Casablanca",
    locale: "fr-MA",
    distanceUnit: "km",
    regionLabel: "Région",
    postalCodeRequired: true,
  },
  SL: {
    currency: "SLE",
    timeZone: "Africa/Freetown",
    locale: "en-SL",
    distanceUnit: "km",
    regionLabel: "Province",
    postalCodeRequired: false,
  },
  LR: {
    currency: "LRD",
    timeZone: "Africa/Monrovia",
    locale: "en-LR",
    distanceUnit: "mi",
    regionLabel: "County",
    postalCodeRequired: false,
  },
  GM: {
    currency: "GMD",
    timeZone: "Africa/Banjul",
    locale: "en-GM",
    distanceUnit: "km",
    regionLabel: "Region",
    postalCodeRequired: false,
  },
  BW: {
    currency: "BWP",
    timeZone: "Africa/Gaborone",
    locale: "en-BW",
    distanceUnit: "km",
    regionLabel: "District",
    postalCodeRequired: false,
  },
  ZM: {
    currency: "ZMW",
    timeZone: "Africa/Lusaka",
    locale: "en-ZM",
    distanceUnit: "km",
    regionLabel: "Province",
    postalCodeRequired: false,
  },
  NA: {
    currency: "NAD",
    timeZone: "Africa/Windhoek",
    locale: "en-NA",
    distanceUnit: "km",
    regionLabel: "Region",
    postalCodeRequired: false,
  },
  GB: {
    currency: "GBP",
    timeZone: "Europe/London",
    locale: "en-GB",
    distanceUnit: "mi",
    regionLabel: "County",
    postalCodeRequired: true,
  },
  IE: {
    currency: "EUR",
    timeZone: "Europe/Dublin",
    locale: "en-IE",
    distanceUnit: "km",
    regionLabel: "County",
    postalCodeRequired: true,
  },
  US: {
    currency: "USD",
    timeZone: "America/New_York",
    locale: "en-US",
    distanceUnit: "mi",
    regionLabel: "State",
    postalCodeRequired: true,
  },
  CA: {
    currency: "CAD",
    timeZone: "America/Toronto",
    locale: "en-CA",
    distanceUnit: "km",
    regionLabel: "Province",
    postalCodeRequired: true,
  },
  FR: {
    currency: "EUR",
    timeZone: "Europe/Paris",
    locale: "fr-FR",
    distanceUnit: "km",
    regionLabel: "Région",
    postalCodeRequired: true,
  },
  DE: {
    currency: "EUR",
    timeZone: "Europe/Berlin",
    locale: "de-DE",
    distanceUnit: "km",
    regionLabel: "Bundesland",
    postalCodeRequired: true,
  },
  NL: {
    currency: "EUR",
    timeZone: "Europe/Amsterdam",
    locale: "nl-NL",
    distanceUnit: "km",
    regionLabel: "Provincie",
    postalCodeRequired: true,
  },
  BE: {
    currency: "EUR",
    timeZone: "Europe/Brussels",
    locale: "fr-BE",
    distanceUnit: "km",
    regionLabel: "Province",
    postalCodeRequired: true,
  },
  ES: {
    currency: "EUR",
    timeZone: "Europe/Madrid",
    locale: "es-ES",
    distanceUnit: "km",
    regionLabel: "Provincia",
    postalCodeRequired: true,
  },
  PT: {
    currency: "EUR",
    timeZone: "Europe/Lisbon",
    locale: "pt-PT",
    distanceUnit: "km",
    regionLabel: "Distrito",
    postalCodeRequired: true,
  },
  IT: {
    currency: "EUR",
    timeZone: "Europe/Rome",
    locale: "it-IT",
    distanceUnit: "km",
    regionLabel: "Provincia",
    postalCodeRequired: true,
  },
  CH: {
    currency: "CHF",
    timeZone: "Europe/Zurich",
    locale: "de-CH",
    distanceUnit: "km",
    regionLabel: "Kanton",
    postalCodeRequired: true,
  },
  SE: {
    currency: "SEK",
    timeZone: "Europe/Stockholm",
    locale: "sv-SE",
    distanceUnit: "km",
    regionLabel: "Län",
    postalCodeRequired: true,
  },
  NO: {
    currency: "NOK",
    timeZone: "Europe/Oslo",
    locale: "nb-NO",
    distanceUnit: "km",
    regionLabel: "Fylke",
    postalCodeRequired: true,
  },
  DK: {
    currency: "DKK",
    timeZone: "Europe/Copenhagen",
    locale: "da-DK",
    distanceUnit: "km",
    regionLabel: "Region",
    postalCodeRequired: true,
  },
  AE: {
    currency: "AED",
    timeZone: "Asia/Dubai",
    locale: "en-AE",
    distanceUnit: "km",
    regionLabel: "Emirate",
    postalCodeRequired: false,
  },
  IN: {
    currency: "INR",
    timeZone: "Asia/Kolkata",
    locale: "en-IN",
    distanceUnit: "km",
    regionLabel: "State",
    postalCodeRequired: true,
  },
  AU: {
    currency: "AUD",
    timeZone: "Australia/Sydney",
    locale: "en-AU",
    distanceUnit: "km",
    regionLabel: "State",
    postalCodeRequired: true,
  },
  BR: {
    currency: "BRL",
    timeZone: "America/Sao_Paulo",
    locale: "pt-BR",
    distanceUnit: "km",
    regionLabel: "Estado",
    postalCodeRequired: true,
  },
  JM: {
    currency: "JMD",
    timeZone: "America/Jamaica",
    locale: "en-JM",
    distanceUnit: "km",
    regionLabel: "Parish",
    postalCodeRequired: false,
  },
};

export function countryDefaults(code: string): CountryDefaults | null {
  return COUNTRY_DEFAULTS[code.toUpperCase()] ?? null;
}
