export type PostsType = {
  id?: string;
  slug?: string;
  title?: string;
  description?: string;
  caegory_id?: number;
  price?: number | string;
  currency?: string;
  location?: string;
  address?: string;
  capacity?: number;
  created_at?: Date;
  organizer_id?: string;
  event_type_id?: number;
  website_url?: string;
  flyer_public_id?: string;
  flyer_version?: string;
  start_at?: Date | string;
  end_at?: Date | string;
  timezone?: string;
  status?: string;
  flyerUrl?: string;
};
