// Generated by apps/mobile/scripts/gen-brand-assets.mjs from the vector
// masters in apps/web/public/assets/images/brand. Do not edit by hand.

export type BrandPart = {
  d: string;
  /** Translation applied to the path, in viewBox units. */
  tx: number;
  ty: number;
  evenOdd: boolean;
  /** "fg" takes the foreground colour, "cut" the mint blade. */
  role: "fg" | "cut";
};

export type BrandArtwork = { viewBox: string; parts: readonly BrandPart[] };

/** The A mark in its three weights: Hero ≥ 64 px, Small 25–63 px, Micro ≤ 24 px. */
export const BRAND_MARK = {
  hero: {
    viewBox: "100 90 800 800",
    parts: [
      {
        d: "M 500 90 L 100 890 L 238.64062 890 L 500 367.26953 L 530.71094 428.69141 C 562.61068 400.46098 594.99427 372.80372 627.86133 345.7207 L 500 90 z M 662.96484 415.92773 C 631.64343 446.15029 600.7584 476.80696 570.31055 507.89453 L 761.35938 890 L 900 890 L 662.96484 415.92773 z",
        tx: 0,
        ty: 0,
        evenOdd: false,
        role: "fg",
      },
      {
        d: "M380.64 606.00 Q605.38 380.07 866.21 196.96 Q557.56 458.85 298.64 770.00 Z",
        tx: 0,
        ty: 0,
        evenOdd: false,
        role: "cut",
      },
    ],
  },
  small: {
    viewBox: "100 90 800 800",
    parts: [
      {
        d: "M 500 90 L 100 890 L 263.23047 890 L 500 416.4707 L 518.37695 453.22266 C 556.51925 421.10358 595.20576 389.65342 634.43555 358.87109 L 500 90 z M 683.28125 456.56055 C 646.53196 492.34604 610.23067 528.56742 574.37891 565.22461 L 736.76953 890 L 900 890 L 683.28125 456.56055 z",
        tx: 0,
        ty: 0,
        evenOdd: false,
        role: "fg",
      },
      {
        d: "M410.23 596.00 Q591.45 430.36 790.34 286.44 L772.45 322.21 Q527.79 548.91 308.23 800.00 Z",
        tx: 0,
        ty: 0,
        evenOdd: false,
        role: "cut",
      },
    ],
  },
  micro: {
    viewBox: "100 90 800 800",
    parts: [
      {
        d: "M 500 90 L 100 890 L 296.76953 890 L 499.75977 484.03125 L 500 483.55078 L 501.51562 480.51953 L 640.42188 370.84375 L 500 90 z M 706.36133 502.7207 L 577.12891 637.80273 L 703.23047 890 L 900 890 L 706.36133 502.7207 z",
        tx: 0,
        ty: 0,
        evenOdd: false,
        role: "fg",
      },
      {
        d: "M446.77 590.00 L755.57 346.18 L724.26 408.79 L332.77 818.00 Z",
        tx: 0,
        ty: 0,
        evenOdd: false,
        role: "cut",
      },
    ],
  },
} as const satisfies Record<"hero" | "small" | "micro", BrandArtwork>;

/** The ABƆNTEN wordmark (plain A), set beside or under the mark. */
export const BRAND_WORDMARK = {
  viewBox: "0 -5 1184 210",
  parts: [
    {
      d: "M98 0 L196 200 L151.46 200 L98 90.91 L44.54 200 L0 200 Z",
      tx: 0,
      ty: 0,
      evenOdd: false,
      role: "fg",
    },
    {
      d: "M61.16 128 L134.84 128 L134.84 162 L61.16 162 Z",
      tx: 0,
      ty: 0,
      evenOdd: false,
      role: "fg",
    },
    {
      d: "M0 0 L40 0 L40 200 L0 200 Z",
      tx: 212,
      ty: 0,
      evenOdd: true,
      role: "fg",
    },
    {
      d: "M0 0 H58 A60 60 0 0 1 58 120 H0 Z M40 40 H58 A20 20 0 0 1 58 80 H40 Z",
      tx: 212,
      ty: 0,
      evenOdd: true,
      role: "fg",
    },
    {
      d: "M0 80 H70 A60 60 0 0 1 70 200 H0 Z M40 120 H70 A20 20 0 0 1 70 160 H40 Z",
      tx: 212,
      ty: 0,
      evenOdd: true,
      role: "fg",
    },
    {
      d: "M 99.427734 -4.8515625 A 105 105 0 0 0 46.199219 13.007812 L 46.199219 78.521484 A 62.6 62.6 0 0 1 167.59961 100 A 62.6 62.6 0 0 1 46.199219 121.47852 L 46.199219 186.99219 A 105 105 0 0 0 210 100 A 105 105 0 0 0 99.427734 -4.8515625 z",
      tx: 314,
      ty: 0,
      evenOdd: false,
      role: "fg",
    },
    {
      d: "M0 0 L40 0 L40 200 L0 200 Z",
      tx: 546,
      ty: 0,
      evenOdd: false,
      role: "fg",
    },
    {
      d: "M118 0 L158 0 L158 200 L118 200 Z",
      tx: 546,
      ty: 0,
      evenOdd: false,
      role: "fg",
    },
    {
      d: "M0 0 L46.44 0 L158 200 L111.56 200 Z",
      tx: 546,
      ty: 0,
      evenOdd: false,
      role: "fg",
    },
    {
      d: "M0 0 L146 0 L146 40 L0 40 Z",
      tx: 716,
      ty: 0,
      evenOdd: false,
      role: "fg",
    },
    {
      d: "M53 0 L93 0 L93 200 L53 200 Z",
      tx: 716,
      ty: 0,
      evenOdd: false,
      role: "fg",
    },
    {
      d: "M0 0 L40 0 L40 200 L0 200 Z",
      tx: 876,
      ty: 0,
      evenOdd: false,
      role: "fg",
    },
    {
      d: "M0 0 L128 0 L128 40 L0 40 Z",
      tx: 876,
      ty: 0,
      evenOdd: false,
      role: "fg",
    },
    {
      d: "M0 80 L115.2 80 L115.2 120 L0 120 Z",
      tx: 876,
      ty: 0,
      evenOdd: false,
      role: "fg",
    },
    {
      d: "M0 160 L128 160 L128 200 L0 200 Z",
      tx: 876,
      ty: 0,
      evenOdd: false,
      role: "fg",
    },
    {
      d: "M0 0 L40 0 L40 200 L0 200 Z",
      tx: 1026,
      ty: 0,
      evenOdd: false,
      role: "fg",
    },
    {
      d: "M118 0 L158 0 L158 200 L118 200 Z",
      tx: 1026,
      ty: 0,
      evenOdd: false,
      role: "fg",
    },
    {
      d: "M0 0 L46.44 0 L158 200 L111.56 200 Z",
      tx: 1026,
      ty: 0,
      evenOdd: false,
      role: "fg",
    },
  ],
} as const satisfies BrandArtwork;
