// Generated by scripts/i18n/gen-catalog-index.mjs — do not edit by hand.
// One import() per namespace the browser may read. The web app sends each
// page the messages it needs; a namespace it did not send (a dialog that
// opens later) is fetched from here as its own cached file. The
// server-only namespaces are not listed, so no bundler ever makes them
// downloadable.

import type { I18nLocale, I18nNamespace } from "./namespaces";

type Messages = Record<string, unknown>;

export const BROWSER_NAMESPACE_LOADERS: Record<
  I18nNamespace,
  (locale: I18nLocale) => Promise<{ default: Messages }>
> = {
  account: (locale) => import(`../messages/${locale}/account.json`),
  auth: (locale) => import(`../messages/${locale}/auth.json`),
  checkout: (locale) => import(`../messages/${locale}/checkout.json`),
  common: (locale) => import(`../messages/${locale}/common.json`),
  core: (locale) => import(`../messages/${locale}/core.json`),
  discovery: (locale) => import(`../messages/${locale}/discovery.json`),
  events: (locale) => import(`../messages/${locale}/events.json`),
  explore: (locale) => import(`../messages/${locale}/explore.json`),
  fatal: (locale) => import(`../messages/${locale}/fatal.json`),
  fieldOps: (locale) => import(`../messages/${locale}/fieldOps.json`),
  finances: (locale) => import(`../messages/${locale}/finances.json`),
  help: (locale) => import(`../messages/${locale}/help.json`),
  landing: (locale) => import(`../messages/${locale}/landing.json`),
  legal: (locale) => import(`../messages/${locale}/legal.json`),
  manage: (locale) => import(`../messages/${locale}/manage.json`),
  messaging: (locale) => import(`../messages/${locale}/messaging.json`),
  metadata: (locale) => import(`../messages/${locale}/metadata.json`),
  navigation: (locale) => import(`../messages/${locale}/navigation.json`),
  notifications: (locale) => import(`../messages/${locale}/notifications.json`),
  places: (locale) => import(`../messages/${locale}/places.json`),
  plans: (locale) => import(`../messages/${locale}/plans.json`),
  profile: (locale) => import(`../messages/${locale}/profile.json`),
  reviews: (locale) => import(`../messages/${locale}/reviews.json`),
  rewards: (locale) => import(`../messages/${locale}/rewards.json`),
  search: (locale) => import(`../messages/${locale}/search.json`),
  settings: (locale) => import(`../messages/${locale}/settings.json`),
  spotlight: (locale) => import(`../messages/${locale}/spotlight.json`),
  tickets: (locale) => import(`../messages/${locale}/tickets.json`),
  transactions: (locale) => import(`../messages/${locale}/transactions.json`),
  validation: (locale) => import(`../messages/${locale}/validation.json`),
  verification: (locale) => import(`../messages/${locale}/verification.json`),
  wallet: (locale) => import(`../messages/${locale}/wallet.json`),
  weekly: (locale) => import(`../messages/${locale}/weekly.json`),
};
