// Generated by scripts/i18n/gen-catalog-index.mjs — do not edit by hand.

export const I18N_LOCALES = ["en", "ak", "de", "es", "fr", "pt"] as const;
export type I18nLocale = (typeof I18N_LOCALES)[number];

export const I18N_NAMESPACES = [
  "auth",
  "common",
  "events",
  "metadata",
  "navigation",
  "places",
  "settings",
] as const;
export type I18nNamespace = (typeof I18N_NAMESPACES)[number];
