// Generated by scripts/i18n/gen-catalog-index.mjs — do not edit by hand.

export const I18N_LOCALES = ["en", "ak", "de", "es", "fr", "pt"] as const;
export type I18nLocale = (typeof I18N_LOCALES)[number];

export const I18N_NAMESPACES = [
  "account",
  "auth",
  "checkout",
  "common",
  "core",
  "discovery",
  "events",
  "explore",
  "fieldOps",
  "finances",
  "help",
  "landing",
  "legal",
  "manage",
  "messaging",
  "metadata",
  "navigation",
  "notifications",
  "places",
  "plans",
  "profile",
  "reviews",
  "rewards",
  "search",
  "settings",
  "spotlight",
  "tickets",
  "transactions",
  "validation",
  "verification",
  "wallet",
  "weekly",
] as const;
export type I18nNamespace = (typeof I18N_NAMESPACES)[number];
