// Generated by scripts/i18n/gen-catalog-index.mjs — do not edit by hand.
// Static catalog map for server code (services, route handlers, emails):
// a synchronous translator needs the messages in memory, not behind an
// import(). Only the namespaces the server speaks are listed.

import akCore from "../messages/ak/core.json";
import akEmails from "../messages/ak/emails.json";
import akServer from "../messages/ak/server.json";
import deCore from "../messages/de/core.json";
import deEmails from "../messages/de/emails.json";
import deServer from "../messages/de/server.json";
import enCore from "../messages/en/core.json";
import enEmails from "../messages/en/emails.json";
import enServer from "../messages/en/server.json";
import esCore from "../messages/es/core.json";
import esEmails from "../messages/es/emails.json";
import esServer from "../messages/es/server.json";
import frCore from "../messages/fr/core.json";
import frEmails from "../messages/fr/emails.json";
import frServer from "../messages/fr/server.json";
import ptCore from "../messages/pt/core.json";
import ptEmails from "../messages/pt/emails.json";
import ptServer from "../messages/pt/server.json";
import type { I18nLocale } from "./namespaces";

export const SERVER_NAMESPACES = ["core", "emails", "server"] as const;
export type ServerNamespace = (typeof SERVER_NAMESPACES)[number];

type Messages = Record<string, unknown>;

export const SERVER_CATALOG: Record<
  I18nLocale,
  Record<ServerNamespace, Messages>
> = {
  en: {
    core: enCore,
    emails: enEmails,
    server: enServer,
  },
  ak: {
    core: akCore,
    emails: akEmails,
    server: akServer,
  },
  de: {
    core: deCore,
    emails: deEmails,
    server: deServer,
  },
  es: {
    core: esCore,
    emails: esEmails,
    server: esServer,
  },
  fr: {
    core: frCore,
    emails: frEmails,
    server: frServer,
  },
  pt: {
    core: ptCore,
    emails: ptEmails,
    server: ptServer,
  },
};
